# Generated by Django 5.0.6 on 2024-07-04 22:40

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='StreetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='Название')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('idCity', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='relicshop.citymodel')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улицы',
                'unique_together': {('name', 'city')},
            },
        ),
        migrations.CreateModel(
            name='ShopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=63, verbose_name='Улица')),
                ('building', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(regex='^\\d+[а-яА-Я]?(\\/\\d+[а-яА-Я]?)?$')], verbose_name='Дом')),
                ('start', models.TimeField(default=datetime.time(0, 0), verbose_name='Время открытия')),
                ('end', models.TimeField(default=datetime.time(23, 59, 59, 999999), verbose_name='Время закрытия')),
                ('idCity', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='relicshop.citymodel')),
                ('idStreet', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='relicshop.streetmodel')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'unique_together': {('name', 'city', 'street', 'building')},
            },
        ),
    ]
