# Generated by Django 5.0.6 on 2024-07-03 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relicshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmodel',
            name='idCity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='relicshop.citymodel'),
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='idStreet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='relicshop.streetmodel'),
        ),
        migrations.AddField(
            model_name='streetmodel',
            name='idCity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='relicshop.citymodel'),
        ),
    ]
