# Generated by Django 5.0.6 on 2024-07-03 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relicshop', '0002_shopmodel_idcity_shopmodel_idstreet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmodel',
            name='idCity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='relicshop.citymodel'),
        ),
        migrations.AlterField(
            model_name='shopmodel',
            name='idStreet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='relicshop.streetmodel'),
        ),
        migrations.AlterField(
            model_name='streetmodel',
            name='idCity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='relicshop.citymodel'),
        ),
    ]
