# Generated by Django 5.0.6 on 2024-07-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relicshop', '0003_alter_shopmodel_idcity_alter_shopmodel_idstreet_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopmodel',
            unique_together={('name', 'city', 'street', 'building')},
        ),
        migrations.AlterUniqueTogether(
            name='streetmodel',
            unique_together={('name', 'city')},
        ),
    ]
