# Generated by Django 5.0.6 on 2024-07-04 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relicshop', '0004_alter_shopmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmodel',
            name='end',
            field=models.TimeField(default=datetime.time(23, 59, 59, 999999), verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='shopmodel',
            name='start',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Время открытия'),
        ),
    ]
